---
- hosts: localhost
  tasks:
    - name: MySQL Install
      package:
        name: mysql-server
        state: latest
    - name: Create a new database
      mysql_db:
        name: {{ item }}
        state: present
        with_items:
          - sample-database
    - mysql_user:
        name: {{ item }}
        password: 3R3xm7kM
        priv: '{{ item }}.*:ALL'
        state: present
        with_items:
          - sample-user